addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
    - python3-pygments
before_install:
  - curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
  - sudo dpkg -i ripgrep_11.0.2_amd64.deb
  - curl -LO https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
dist: bionic
language: bash
sudo: false

script: bats test
