sudo: false
language: bash
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
    - pandoc
    - python3-pygments
before_install:
  # rust
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  # ripgrep
  - cargo install ripgrep

script: bats test
